# Generated by Django 6.0.1 on 2026-04-01 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0, help_text='Risk score 0–100')),
                ('verdict', models.CharField(choices=[('safe', 'Safe'), ('suspicious', 'Suspicious'), ('phishing', 'Phishing')], default='safe', max_length=20)),
                ('reason_codes', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('rules_applied', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Mailbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('ms_user_id', models.CharField(help_text='Microsoft Graph user ID', max_length=255)),
                ('is_vip', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('quarantine', 'Quarantine'), ('label_suspicious', 'Label Suspicious'), ('no_action', 'No Action')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='email_phishing_defender.detection')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('false_positive', 'False Positive'), ('false_negative', 'False Negative'), ('confirmed', 'Confirmed')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='email_phishing_defender.detection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phishing_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ms_message_id', models.CharField(help_text='Microsoft Graph message ID', max_length=512, unique=True)),
                ('sender_email', models.EmailField(max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('reply_to', models.EmailField(blank=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=1024)),
                ('body_text', models.TextField(blank=True)),
                ('body_html', models.TextField(blank=True)),
                ('received_at', models.DateTimeField()),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('attachments_meta', models.JSONField(blank=True, default=list)),
                ('is_processed', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mailbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='email_phishing_defender.mailbox')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detection', to='email_phishing_defender.message'),
        ),
        migrations.CreateModel(
            name='MessageLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2048)),
                ('display_text', models.CharField(blank=True, max_length=2048)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='email_phishing_defender.message')),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.CharField(help_text='Microsoft tenant ID', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('_access_token', models.TextField(blank=True, db_column='access_token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='mailbox',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailboxes', to='email_phishing_defender.tenant'),
        ),
        migrations.CreateModel(
            name='BlockList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_list', to='email_phishing_defender.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AllowList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('reason', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allow_list', to='email_phishing_defender.tenant')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['ms_message_id'], name='email_phish_ms_mess_677c65_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['mailbox', 'received_at'], name='email_phish_mailbox_6605a6_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_processed'], name='email_phish_is_proc_d0a61a_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['verdict'], name='email_phish_verdict_837592_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['score'], name='email_phish_score_b5d568_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mailbox',
            unique_together={('tenant', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='blocklist',
            unique_together={('tenant', 'domain')},
        ),
        migrations.AlterUniqueTogether(
            name='allowlist',
            unique_together={('tenant', 'domain')},
        ),
    ]
