# Generated by Django 6.0.1 on 2026-04-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_phishing_defender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='llm_explanation',
            field=models.JSONField(blank=True, default=dict, help_text='LLM-generated explanation: summary, reasons, risk_level, user_advice'),
        ),
    ]
